<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Date' => 'Ժամանակ',
    'ID' => 'Համար',
    'Name' => 'Անուն',
    'Phone' => 'Հեռ.',
    'Surname' => 'Ազգանուն',
    'Totalprice' => 'Արժեք',
     'Are you sure you want to delete this item?' => 'Դուք համոզված եք որ ուզւմ եք ջնջել սա ?',
    'Categories' => 'Կատեգորիաներ',
    'Create' => 'Ստեղծել',
    'Create Order' => 'Ստեղծել Առաջարկություն',
    'Create Page' => 'Ստեղծոլ էջ',
    'Create User' => 'Ստեղծել Օգտագործող',
    'Delete' => 'Ջնջել',
    'Orders' => 'Առաջարկություններ',
    'Pages' => 'Էջէր',
    'Update' => 'Թարմացնել',
    'Update {modelClass}: ' => 'Թարմացնել {modelClass}',
    'User  ' => 'Օգտագործող',
    'Prices' => 'Գներ',
    'Trips' => 'Ուղեւորություններ',
];
